replicaCount: 2

image:
  repository: perish95/argocd-project  # 본인 Docker Hub ID 입력
  pullPolicy: IfNotPresent
  tag: "4"  # CI에 의해 빌드 번호(예: 0 -> 1 -> 2 -> ...)로 자동 수정되는 부분

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080  # Spring Boot App 포트

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs: []
  hostnames: []
  rules: []